# 01 Numpy. Пшенин Владислав Игоревич 6133

In [1]:
import numpy as np

## I. Взять из документации по numpy 12 любых функций / методов / операторов и продемонстрировать из работу в блокноте

**1) Creating array**

In [7]:
a = np.arange(15).reshape(5, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

**2) Some information about array**

In [9]:
a.ndim, a.shape, a.dtype

(2, (5, 3), dtype('int32'))

**3) Creating array (diff way)**

In [11]:
a = np.ones( (4,4,8), dtype=np.int16 )
a

array([[[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]]], dtype=int16)

In [23]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**4) Arithmetic operators (Exponentiation)**

In [24]:
b = b**2
b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

**5) Arithmetic operators (Relational)**

In [25]:
b<20

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

**6) Arithmetic operators (Multiplication)**

In [26]:
b*b

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561],
      dtype=int32)

**7) Arithmetic operators (Sin)**

In [28]:
10*np.sin(b)

array([ 0.        ,  8.41470985, -7.56802495,  4.12118485, -2.87903317,
       -1.3235175 , -9.91778853, -9.53752653,  9.20026038, -6.29887994])

**8) Creating array (random)**

In [30]:
a = np.random.random((2,3))
a

array([[0.75413466, 0.18769748, 0.87950403],
       [0.22371645, 0.36033643, 0.57764833]])

**9) Sum, min, max**

In [35]:
a.sum(),a.min(),a.max()

(2.98303738327656, 0.18769747504281087, 0.8795040335842005)

**10) Array sorting**

In [34]:
np.sort(a)

array([[0.18769748, 0.75413466, 0.87950403],
       [0.22371645, 0.36033643, 0.57764833]])

**11) Mean, median, std**

In [36]:
a.mean(), np.median(a), np.std(a)

(0.49717289721276003, 0.4689923791330427, 0.26075545003494865)

**12) Concatenate arrays**

In [40]:
np.concatenate((a,a), axis=1) 

array([[0.75413466, 0.18769748, 0.87950403, 0.75413466, 0.18769748,
        0.87950403],
       [0.22371645, 0.36033643, 0.57764833, 0.22371645, 0.36033643,
        0.57764833]])

## II. Сгенерировать OLAP-куб, где фиксируем продажи товаров в розничной сети по магазинам

**OLAP-куб**

Оси:
* 0: ID группы товаров (100)
* 1: ID магазина (10)
* 2: день месяца, в котором осуществляются продажи (31)

In [173]:
olap = np.zeros((100,10,31))

In [174]:
for i in range (olap.shape[0]):
    a = np.random.randint(1,101)
    for j in range (olap.shape[1]):
        b = a + a * np.random.rand()
        for k in range (olap.shape[2]):
            olap[i][j][k] = b * np.random.randint(1,10)
            

## III. Для получившегося OLAP-куба посчитать суммарные, средние, минимальные и максимальные продажи (на самом деле любые агрегатные функции можно использовать), зафиксировав значения по одной, двум или трём осям

**Срез для 0-товара по всем дням и магазинам**

In [175]:
olap[0,:,:]

array([[ 98.08223581, 294.24670742,  65.3881572 , 163.47039301,
        163.47039301, 163.47039301, 261.55262882, 294.24670742,
        130.77631441, 261.55262882,  65.3881572 , 196.16447161,
        196.16447161,  32.6940786 , 228.85855022,  98.08223581,
         32.6940786 , 261.55262882,  98.08223581, 196.16447161,
        228.85855022, 294.24670742,  98.08223581,  65.3881572 ,
        130.77631441, 130.77631441,  32.6940786 ,  98.08223581,
        228.85855022, 261.55262882, 196.16447161],
       [ 96.45984404,  96.45984404, 289.37953212, 289.37953212,
        128.61312539,  64.30656269,  32.15328135, 225.07296943,
         64.30656269,  96.45984404,  64.30656269,  96.45984404,
        257.22625077, 160.76640673, 128.61312539, 289.37953212,
        225.07296943,  96.45984404, 128.61312539,  32.15328135,
         32.15328135, 128.61312539,  64.30656269, 160.76640673,
        160.76640673, 128.61312539,  32.15328135, 192.91968808,
        225.07296943, 225.07296943,  64.30656269],
  

In [176]:
print("Максимум= " + str(olap[0,:,:].max()))
print("Минимум= " + str(olap[0,:,:].min()))
print("Среднее= " + str(olap[0,:,:].mean()))

Максимум= 516.9552871330447
Минимум= 32.153281346714984
Среднее= 217.61745856112796


**Максимумы продаж по дням 0-товара для всех магазаинов**

In [177]:
print("Максимумы = " + str(olap[0,:,:].max(axis = 1)))

Максимумы = [294.24670742 289.37953212 516.95528713 502.04219422 392.02013653
 392.82086819 427.17017852 423.36158546 324.6959173  443.11652466]


**Среднемесячные продажи 10-товара для всех магазаинов**

In [178]:
print("Среднее = " + str(olap[10,:,:].mean(axis = 1)))

Среднее = [305.07178682 182.61370176 153.42506435 189.63711223 282.45803911
 222.88413106 160.53342542 234.52207549 163.4703015  324.2560276 ]


**Cумма, максимум, минимум и среднее по продажам 10-20 чисел месяца для товаров [1,3,4] по всем магазинам**

In [179]:
print("Сумма= " + str(olap[[1,3,4],:,10:21].sum()))
print("Максимум= " + str(olap[[1,3,4],:,10:21].max()))
print("Минимум= " + str(olap[[1,3,4],:,10:21].min()))
print("Среднее= " + str(olap[[1,3,4],:,10:21].mean()))

Сумма= 107812.49406513816
Максимум= 1616.5667589059512
Минимум= 19.053951004076684
Среднее= 326.70452747011564


**Cумма, максимум, минимум и среднее по продажам 0-15 чисел месяца для товаров 26-53 по магазинам 2-7**

In [180]:
print("Сумма= " + str(olap[26:54,2:8,:16].sum()))
print("Максимум= " + str(olap[26:54,2:8,:16].max()))
print("Минимум= " + str(olap[26:54,2:8,:16].min()))
print("Среднее= " + str(olap[26:54,2:8,:16].mean()))

Сумма= 1069265.4937293502
Максимум= 1770.7170523871343
Минимум= 6.876431432479832
Среднее= 397.7922223695499


**Сумма продаж для всех товаров в день для каждого магазина**

In [152]:
np.sum(olap, axis = 0)  

array([[42745.00723478, 42688.39902274, 41610.85102552, 44482.61805958,
        44620.70057191, 42355.61197492, 42821.50063588, 37445.15365544,
        42752.64911509, 45436.84887035, 37870.13375099, 42547.53691754,
        45833.78673053, 40773.19516476, 40738.43889132, 40302.08256239,
        44790.95186034, 40506.93309252, 39970.58994492, 41614.02288586,
        36647.6568576 , 38842.3865137 , 38670.31261337, 33778.31258272,
        40552.19305714, 42193.33177074, 42434.9370546 , 43032.39126504,
        40714.90269921, 41161.23944565, 37140.7329824 ],
       [41073.42113869, 41425.83839509, 39484.54086586, 40046.7989963 ,
        38870.51234055, 40601.07471656, 41832.47634238, 39267.9617385 ,
        36844.05374288, 39349.71554886, 40333.29636599, 43226.34075402,
        41519.50618864, 39408.86246189, 39861.08468652, 38593.44464983,
        38168.14521951, 41860.47510861, 38196.17151369, 42085.81284888,
        43171.40559683, 41659.61590088, 43867.0483954 , 39276.88396202,
       